FROM registry.fedoraproject.org/fedora 

# Without `libglvnd-gles` gnome-calculator will error out with:
# libEGL warning: wayland-egl: could not open /dev/dri/renderD128 (No such file or directory)
# Couldn't open libGLESv2.so.2: libGLESv2.so.2: cannot open shared object file: No such file or directory
RUN dnf install -y gnome-calculator libglvnd-gles dbus-x11

CMD ["/usr/bin/gnome-calculator"]
